name: Bug Report
description: Found a bug?
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        We're sorry to hear you have a problem.

        Before submitting your report, please make sure you've been through the [Documentation](https://docs.nativecli.com).

        If nothing here has helped you, please provide as much useful context as you can here to help us solve help you.

        Note that reams and reams of logs isn't helpful - please share only relevant errors.
  - type: textarea
    id: what-doing
    attributes:
      label: What were you trying to do?
      description: Some context about what you were trying to achieve
      placeholder: Trying to install a new NativePHP project
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: I cannot currently run X because when I do, it throws X error.
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce the bug
      description: How did this occur, please add any config values used and provide a set of reliable steps if possible.
      placeholder: When I do X I see Y.
    validations:
      required: true
  - type: textarea
    id: package-version
    attributes:
      label: Package Versions
      description: What version are you running? Output of `nativecli --version`
    validations:
      required: true
  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you running?
      placeholder: 8.2.0
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node Version
      description: What version of Node are you running? Please be as specific as possible
      placeholder: '18.17'
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: Which operating systems have you seen this occur on?
      description: You may select more than one.
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
  - type: input
    id: os-version
    attributes:
      label: OS version
      description: Which version of these OSes are you using?
      placeholder: 'win11 (23H2), macos14.1 (23B74)'
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Use this field to provide any other notes that you feel might be relevant to the issue. Include links to any reproduction repos you've created here.
    validations:
      required: false
